
service: tweetpress

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
functions:
  favourite:
    handler: handler.favourite
    events:
     - http:
         path: /favourite
         method: get
         cors: false
      